const PRODUCTS = [

  // ── HIKVISION ──────────────────────────────
  {
    id: 1,
    name: "DS-2CD1143G2-I",
    brand: "Hikvision",
    category: "outdoor",
    tag: "Hikvision",
    tagColor: "#e53935",
    subtitle: "4MP AcuSense Fixed Dome Network Camera",
    image: "hikvision_1.jpg",
    images: ["hikvision_1.jpg", "hikvision_2.jpg", "hikvision_3.jpg"],
    shortDesc: "4MP AcuSense Fixed Dome — Human & Vehicle Detection, IR 40m.",
    description: "The DS-2CD1143G2-I is a 4MP AcuSense Fixed Dome Network Camera featuring deep learning-based human and vehicle detection. With 40m IR night vision and H.265+ compression, it delivers superior image quality with reduced false alarms.",
    highlights: ["4MP Resolution", "AcuSense – Human & Vehicle Detection", "IR Night Vision 40m", "H.265+ Compression", "IP67 Weatherproof", "IK10 Vandal Resistant"],
    specs: [
      { label: "Model", value: "DS-2CD1143G2-I" },
      { label: "Image Sensor", value: "1/3\" Progressive Scan CMOS" },
      { label: "Max. Resolution", value: "2560 × 1440 (4MP)" },
      { label: "Min. Illumination", value: "Color: 0.01 Lux @ (F1.2, AGC ON) | 0 Lux with IR" },
      { label: "Shutter Speed", value: "1/3s – 1/100,000s" },
      { label: "Lens", value: "2.8mm / 4mm Fixed" },
      { label: "Angle of View", value: "2.8mm: 103° | 4mm: 78°" },
      { label: "IR Range", value: "Up to 40m" },
      { label: "Video Compression", value: "H.265+ / H.265 / H.264+ / H.264" },
      { label: "Max. Frame Rate", value: "25fps (2560×1440)" },
      { label: "Day/Night", value: "Auto ICR" },
      { label: "WDR", value: "120 dB" },
      { label: "Video Output", value: "1 RJ45 10M/100M Ethernet" },
      { label: "Weatherproof", value: "IP67" },
      { label: "Vandal Resistant", value: "IK10" },
      { label: "Power Supply", value: "12V DC / PoE (802.3af)" },
      { label: "Dimensions", value: "Φ122.4 × 87.7 mm" }
    ],
    inBox: ["1x Dome Camera", "Mounting Template", "Screws & Anchors", "Waterproof Accessories", "Quick Start Guide", "Warranty Card"]
  },
  {
    id: 2,
    name: "DS-2CD2T47G2-L",
    brand: "Hikvision",
    category: "outdoor",
    tag: "Hikvision",
    tagColor: "#e53935",
    subtitle: "4MP ColorVu Fixed Turret Network Camera",
    image: "hikvision_2.jpg",
    images: ["hikvision_2.jpg", "hikvision_1.jpg", "hikvision_3.jpg"],
    shortDesc: "4MP ColorVu Bullet — Full Color Night Vision, Built-in Mic, IR 60m.",
    description: "The DS-2CD2T47G2-L ColorVu camera provides vivid full-color imaging even in low-light conditions. Equipped with a built-in microphone and advanced H.265+ compression, it offers excellent 24/7 color surveillance for outdoor perimeter protection.",
    highlights: ["4MP Full Color Night Vision", "Built-in Microphone", "IR Range 60m", "H.265+ Compression", "IP67 Rated", "AcuSense Technology"],
    specs: [
      { label: "Model", value: "DS-2CD2T47G2-L" },
      { label: "Image Sensor", value: "1/2.7 inch Progressive Scan CMOS" },
      { label: "Max. Resolution", value: "2688 × 1520 (4MP)" },
      { label: "Min. Illumination", value: "Color: 0.0005 Lux @ F1.6 | 0 Lux with IR" },
      { label: "Lens", value: "2.8mm / 4mm / 6mm Fixed" },
      { label: "Angle of View", value: "4mm: H 84°, V 54°, D 100°" },
      { label: "IR Range", value: "Up to 60m (ColorVu)" },
      { label: "Video Compression", value: "H.265+ / H.265 / H.264+ / H.264" },
      { label: "Max. Frame Rate", value: "25fps (2688×1520)" },
      { label: "Audio", value: "Built-in Mic, 1 Audio Input/Output" },
      { label: "Day/Night", value: "Color 24/7 (ColorVu)" },
      { label: "WDR", value: "130 dB" },
      { label: "Weatherproof", value: "IP67" },
      { label: "Power Supply", value: "12V DC / PoE (802.3af)" },
      { label: "Dimensions", value: "94.4 × 94.4 × 267.6 mm" }
    ],
    inBox: ["1x Bullet Camera", "Mounting Bracket", "Screws & Anchors", "Waterproof Accessories", "Quick Start Guide", "Warranty Card"]
  },

  // ── CP PLUS CAMERAS ────────────────────────
  {
    id: 3,
    name: "CP-URC-TC24PL3",
    brand: "CP Plus",
    category: "outdoor",
    tag: "CP Plus",
    tagColor: "#1565c0",
    subtitle: "2.4MP IR Bullet Camera – 30Mtr.",
    image: "outdoor_1.jpg",
    images: ["outdoor_1.jpg", "outdoor_2.jpg", "outdoor_3.jpg"],
    shortDesc: "2.4MP PS CMOS Bullet Camera — Day/Night ICR, IR 30m, IP67.",
    description: "The CP-URC-TC24PL3 is a 2.4MP IR Bullet Camera with PS CMOS image sensor delivering max 2.4MP (1920×1080/25fps) resolution. Features Day/Night ICR, 2D-DNR, AWB, AGC, BLC and a 3.6mm fixed lens for wide-angle surveillance.",
    highlights: ["2.4MP PS CMOS Sensor", "IR Night Vision 30m", "Day/Night ICR", "2D-DNR, AWB, AGC, BLC", "3.6mm Fixed Lens", "CVI/CVBS/AHD/TVI Switchable"],
    specs: [
      { label: "Model", value: "CP-URC-TC24PL3" },
      { label: "Image Sensor", value: "2.4MP PS CMOS Image Sensor" },
      { label: "Max. Resolution", value: "1920 × 1080 / 25fps" },
      { label: "Min. Illumination", value: "0.02 Lux@F2.0 (Color) | 0 Lux@F2.0 (IR on)" },
      { label: "Shutter Speed", value: "PAL: 1/25s – 1/100,000s | NTSC: 1/30s – 1/100,000s" },
      { label: "Lens", value: "3.6mm Fixed (2.8mm and 6mm optional)" },
      { label: "Angle of View", value: "Pan: 0°–360° | Tilt: 0°–90° | Rotation: 0°–360°" },
      { label: "Lens Type", value: "Fixed/Varifocal" },
      { label: "Lens Mount", value: "M12" },
      { label: "Max. Aperture", value: "F2.0" },
      { label: "IR Range", value: "30 Mtrs." },
      { label: "IR Mode", value: "Smart IR" },
      { label: "Day/Night", value: "Auto (ICR) / Manual" },
      { label: "Video Output", value: "CVI/TVI/AHD/CVBS by one BNC port" },
      { label: "Noise Reduction", value: "2D-DN" },
      { label: "Gain Control (AGC)", value: "Auto" },
      { label: "Video Compression", value: "H.265+ / H.264" },
      { label: "Operating Temperature", value: "-40°C – +60°C (-40°F – +140°F)" },
      { label: "Power Source", value: "12V DC ±30%" },
      { label: "Dimension", value: "144.1 mm × 70.0 mm × 60.8 mm" },
      { label: "Weight", value: "0.15 kg" }
    ],
    inBox: ["1x Bullet Camera", "Mounting Bracket", "Screws & Anchors", "User Manual", "Warranty Card"]
  },
  {
    id: 4,
    name: "CP-USC-TC51PL3C",
    brand: "CP Plus",
    category: "outdoor",
    tag: "CP Plus",
    tagColor: "#1565c0",
    subtitle: "5MP IR Bullet Camera – 30Mtr.",
    image: "outdoor_2.jpg",
    images: ["outdoor_2.jpg", "outdoor_1.jpg", "outdoor_3.jpg"],
    shortDesc: "5MP IR Bullet Camera — DWDR, Built-in Mic, Smart IR 30m, IP67.",
    description: "The CP-USC-TC51PL3C is a 5MP IR Bullet Camera with 1/2.7 inch 5MP P5 CMOS image sensor. Features DWDR, Day/Night ICR, 2D-DNR, AWB, BLC, HLC and support for Built-in Mic. Ideal for outdoor surveillance with 30m Smart IR range.",
    highlights: ["5MP P5 CMOS Sensor", "Smart IR 30m, IP67", "Support Built-in Mic", "DWDR / Day/Night ICR", "2D-DNR, AWB, BLC, HLC", "CVI/CVBS/AHD/TVI Switchable"],
    specs: [
      { label: "Model", value: "CP-USC-TC51PL3C" },
      { label: "Image Sensor", value: "1/2.7 inch 5MP P5 CMOS Image Sensor (0.9407 cm)" },
      { label: "Max. Resolution", value: "2880 (H) × 1620 (V)" },
      { label: "Min. Illumination", value: "0.02 Lux/F2.0, 30 IRE, 0 Lux IR on" },
      { label: "Shutter Speed", value: "PAL: 1/25s – 1/100,000s | NTSC: 1/30s – 1/100,000s" },
      { label: "Lens", value: "3.6mm fixed lens (2.8mm optional)" },
      { label: "Lens Type", value: "Fixed" },
      { label: "Angle of View", value: "3.6mm: 104° × 88° × 46° | 2.8mm: 125° × 106° × 56°" },
      { label: "Close Focus Distance", value: "3.6mm: 1.2m | 2.8mm: 0.8m" },
      { label: "DORI Distance", value: "3.6mm: 80m(Detect) 32m(Observe) 16m(Recognize) 8m(Identify)" },
      { label: "IR Range", value: "30 Mtrs., IP67" },
      { label: "IR Mode", value: "Smart IR" },
      { label: "Day/Night", value: "Auto (ICR) / Manual" },
      { label: "Audio Interface", value: "Audio Interface (Built-in Mic)" },
      { label: "Video Compression", value: "H.265+ / H.264" },
      { label: "Resolution", value: "5M(2880×1620), 4M(2560×1440), 2M(1920×1080), 960H" },
      { label: "Frame Rate", value: "CVI: PAL 5M@25fps | NTSC: 5M@25fps | AHD: 4M@25fps" },
      { label: "Noise Reduction", value: "2D DNR" },
      { label: "Power Source", value: "12V DC ±30%" },
      { label: "Operating Temperature", value: "-40°C – +60°C" }
    ],
    inBox: ["1x Bullet Camera", "Mounting Bracket", "Screws & Anchors", "User Manual", "Warranty Card"]
  },
  {
    id: 5,
    name: "CP-URC-DC24PL3",
    brand: "CP Plus",
    category: "indoor",
    tag: "CP Plus",
    tagColor: "#1565c0",
    subtitle: "2.4MP IR Dome Camera – 20Mtr.",
    image: "combo_1.jpg",
    images: ["combo_1.jpg", "combo_2.jpg", "combo_3.jpg"],
    shortDesc: "2.4MP IR Dome Camera — Indoor/Outdoor, IR 20m, Day/Night ICR.",
    description: "The CP-URC-DC24PL3 is a compact 2.4MP IR Dome Camera suitable for indoor and outdoor installations. With a 2.4MP CMOS sensor and IR night vision up to 20m, it provides reliable 24/7 surveillance for homes, offices and retail stores.",
    highlights: ["2.4MP CMOS Sensor", "IR Night Vision 20m", "Day/Night ICR", "IP66 Weatherproof", "Compact Dome Design", "Easy Ceiling Mount"],
    specs: [
      { label: "Model", value: "CP-URC-DC24PL3" },
      { label: "Image Sensor", value: "2.4MP CMOS Image Sensor" },
      { label: "Max. Resolution", value: "1920 × 1080 / 25fps" },
      { label: "Min. Illumination", value: "0.02 Lux@F2.0 (Color) | 0 Lux (IR on)" },
      { label: "Lens", value: "3.6mm Fixed" },
      { label: "Angle of View", value: "H: 87.3° | V: 46.2° | D: 101.4°" },
      { label: "IR Range", value: "20 Mtrs." },
      { label: "IR Mode", value: "Smart IR" },
      { label: "Day/Night", value: "Auto (ICR) / Manual" },
      { label: "Video Output", value: "CVI/TVI/AHD/CVBS by one BNC port" },
      { label: "Noise Reduction", value: "2D-DNR" },
      { label: "Weatherproof", value: "IP66" },
      { label: "Power Source", value: "12V DC ±30%" },
      { label: "Dimensions", value: "Φ105 mm × 80 mm" },
      { label: "Weight", value: "0.20 kg" }
    ],
    inBox: ["1x Dome Camera", "Mounting Screws", "Anchor Bolts", "User Manual", "Warranty Card"]
  },
  {
    id: 6,
    name: "CP-UVR-1601K2-I3",
    brand: "CP Plus",
    category: "kit",
    tag: "DVR",
    tagColor: "#6d4c41",
    subtitle: "16Ch. 5M-N/1080P Digital Video Recorder",
    image: "kit_1.jpg",
    images: ["kit_1.jpg", "kit_2.jpg", "combo_1.jpg"],
    shortDesc: "16Ch DVR — 5M-N/1080P Recording, H.265+, Mobile Viewing, HDD Support.",
    description: "The CP-UVR-1601K2-I3 is a 16-Channel Digital Video Recorder supporting 5M-N and 1080P resolution recording. With H.265+ compression, it reduces storage requirements while maintaining high image quality. Supports up to 2 SATA HDDs and remote mobile viewing.",
    highlights: ["16 Channel DVR", "5M-N / 1080P Recording", "H.265+ Compression", "Mobile Live View", "Supports 2x SATA HDD", "CVI/TVI/AHD/CVBS/IP Compatible"],
    specs: [
      { label: "Model", value: "CP-UVR-1601K2-I3" },
      { label: "Type", value: "16 Ch. Digital Video Recorder" },
      { label: "Video Compression", value: "H.265+ / H.265 / H.264+ / H.264" },
      { label: "Recording Resolution", value: "5M-N / 4M-N / 1080P / 720P / WD1 / 4CIF / CIF" },
      { label: "Video Input", value: "16 Channel BNC" },
      { label: "Audio Input", value: "4 Channel RCA" },
      { label: "HDD Interface", value: "2× SATA (Max 8TB each)" },
      { label: "Network Interface", value: "1× RJ45 10M/100Mbps Ethernet" },
      { label: "USB", value: "2× USB 2.0" },
      { label: "HDMI Output", value: "1× HDMI 1080P" },
      { label: "VGA Output", value: "1× VGA 1080P" },
      { label: "Mobile App", value: "gCMOB / VMEYE" },
      { label: "Operating Temp.", value: "-10°C – +55°C" },
      { label: "Power Supply", value: "12V DC, 3A" },
      { label: "Dimensions", value: "260 mm × 215 mm × 45 mm" }
    ],
    inBox: ["1x DVR Unit", "Power Adapter", "SATA Data Cable", "Mouse", "Remote Control", "Quick Guide", "Warranty Card"]
  },
  {
    id: 7,
    name: "CP-URC-TC51PL3C-L-V2",
    brand: "CP Plus",
    category: "outdoor",
    tag: "Dual Light",
    tagColor: "#f57c00",
    subtitle: "5MP Dual Light Bullet Camera – 30Mtr.",
    image: "outdoor_3.jpg",
    images: ["outdoor_3.jpg", "outdoor_1.jpg", "outdoor_2.jpg"],
    shortDesc: "5MP Dual Light Bullet — Color Night Vision + IR, Smart IR 30m.",
    description: "The CP-URC-TC51PL3C-L-V2 is a 5MP Dual Light Bullet Camera from the Orange illumax series. It supports both white light for color night vision and IR for standard night vision, giving you the flexibility to choose based on your security needs.",
    highlights: ["5MP Dual Light Technology", "Color Night Vision (White Light)", "Smart IR 30m", "IP67 Weatherproof", "Built-in Mic Support", "CVI/TVI/AHD/CVBS"],
    specs: [
      { label: "Model", value: "CP-URC-TC51PL3C-L-V2" },
      { label: "Series", value: "Orange – Analog illumax" },
      { label: "Image Sensor", value: "5MP P5 CMOS Image Sensor" },
      { label: "Max. Resolution", value: "2880 × 1620 (5MP)" },
      { label: "Min. Illumination", value: "0.005 Lux (Color) | 0 Lux (IR on)" },
      { label: "Lens", value: "3.6mm Fixed" },
      { label: "Angle of View", value: "H: 104° | V: 88° | D: 46°" },
      { label: "IR Range", value: "30 Mtrs. (Dual Light)" },
      { label: "White Light Range", value: "30 Mtrs." },
      { label: "Day/Night", value: "Auto / Color 24×7 / IR" },
      { label: "Audio", value: "Built-in Mic" },
      { label: "Weatherproof", value: "IP67" },
      { label: "Video Output", value: "CVI/TVI/AHD/CVBS" },
      { label: "Power Source", value: "12V DC ±30%" }
    ],
    inBox: ["1x Dual Light Bullet Camera", "Mounting Bracket", "Screws", "User Manual", "Warranty Card"]
  },
  {
    id: 8,
    name: "CP-URC-DC51PL3C-L",
    brand: "CP Plus",
    category: "indoor",
    tag: "Dual Light",
    tagColor: "#f57c00",
    subtitle: "5MP Dual Light Dome Camera – 30Mtr.",
    image: "combo_2.jpg",
    images: ["combo_2.jpg", "combo_3.jpg", "combo_1.jpg"],
    shortDesc: "5MP Dual Light Dome — Color + IR Night Vision, 30m, IP67.",
    description: "The CP-URC-DC51PL3C-L is a 5MP Dual Light Dome Camera from the Orange illumax series. Suitable for both indoor and outdoor installation, it provides full-color night vision with white light and IR night vision, delivering superior 24/7 surveillance.",
    highlights: ["5MP Dual Light Dome", "Full Color Night Vision", "Smart IR 30m", "IP67 Weatherproof", "Compact Dome Design", "IK10 Vandal Resistant"],
    specs: [
      { label: "Model", value: "CP-URC-DC51PL3C-L" },
      { label: "Series", value: "Orange – Analog illumax" },
      { label: "Image Sensor", value: "5MP CMOS Image Sensor" },
      { label: "Max. Resolution", value: "2880 × 1620 (5MP)" },
      { label: "Min. Illumination", value: "0.005 Lux (Color) | 0 Lux (IR on)" },
      { label: "Lens", value: "3.6mm Fixed" },
      { label: "IR Range", value: "30 Mtrs." },
      { label: "White Light", value: "30 Mtrs." },
      { label: "Day/Night", value: "Auto / Color / IR" },
      { label: "Weatherproof", value: "IP67" },
      { label: "Vandal Resistant", value: "IK10" },
      { label: "Video Output", value: "CVI/TVI/AHD/CVBS" },
      { label: "Power Source", value: "12V DC ±30%" }
    ],
    inBox: ["1x Dome Camera", "Mounting Template", "Screws", "User Manual", "Warranty Card"]
  },
  {
    id: 9,
    name: "Mini Hidden WiFi Camera",
    brand: "Generic",
    category: "wifi",
    tag: "Hidden Cam",
    tagColor: "#7b1fa2",
    subtitle: "1080P Mini Spy Camera – Night Vision, Built-in Mic",
    image: "mini1.png",
    images: ["mini1.png", "mini2.png", "mini3.png"],
    shortDesc: "Thumb-size WiFi camera — Night Vision, Inbuilt Mic, Live view on phone.",
    description: "This ultra-compact Mini Hidden WiFi Camera is barely visible yet incredibly powerful. With built-in night vision infrared LEDs and inbuilt microphone, it records clear HD video even in complete darkness. Magnetic base allows placement anywhere. View live footage on your phone 24/7.",
    highlights: ["1080p Full HD Recording", "Night Vision (IR LEDs)", "Inbuilt Microphone", "Live View on Phone", "Ultra Compact – Thumb Size", "Magnetic Mount"],
    specs: [
      { label: "Model", value: "Mini Spy WiFi Camera" },
      { label: "Resolution", value: "1080P Full HD" },
      { label: "Image Sensor", value: "CMOS" },
      { label: "Night Vision", value: "Yes – Infrared IR LEDs" },
      { label: "Microphone", value: "Built-in Mic (Audio Recording)" },
      { label: "Connectivity", value: "WiFi 2.4GHz" },
      { label: "Mobile App", value: "Android & iOS" },
      { label: "Storage", value: "MicroSD Card up to 128GB" },
      { label: "Battery", value: "Built-in Rechargeable (200mAh)" },
      { label: "Charging", value: "USB Type-C" },
      { label: "Dimensions", value: "Ultra Compact (Approx. 32 × 32 mm)" },
      { label: "Mount", value: "Magnetic Base" }
    ],
    inBox: ["1x Mini Camera", "USB Charging Cable", "Magnetic Mount Stand", "User Manual"]
  }
  ,
  {
    id: 10,
    name: "CP-UNR-4K2081-V4",
    brand: "CP Plus",
    category: "kit",
    tag: "NVR",
    tagColor: "#1565c0",
    subtitle: "8 Ch. 4K Network Video Recorder",
    image: "nvr_8ch.png",
    images: ["nvr_8ch.png", "dvr_box.png", "kit_8cam.png"],
    shortDesc: "8Ch 4K NVR — AI by NVR/Camera, H.265, iCMOB/gCMOB App.",
    description: "The CP-UNR-4K2081-V4 is an 8-channel 4K Network Video Recorder with industrial-grade performance. Features AI by NVR supporting 4-channel IMD, AI by Camera for perimeter protection, and Instastream technology for seamless remote viewing via iCMOB/gCMOB mobile apps.",
    highlights: [
      "8 Channel IP Camera Input",
      "4K Ultra HD Recording",
      "AI by NVR – 4 Channel IMD",
      "AI by Camera – Perimeter Protection",
      "1 SATA HDD up to 20TB",
      "Mobile App: iCMOB, gCMOB"
    ],
    specs: [
      { label: "Model", value: "CP-UNR-4K2081-V4" },
      { label: "Type", value: "8 Ch. 4K Network Video Recorder" },
      { label: "IP Camera Input", value: "Up to 8 Channel" },
      { label: "Video Compression", value: "Instastream, H.265, H.264+, H.264, MJPEG" },
      { label: "Max. Decoding", value: "6 × 1080p@30fps" },
      { label: "Bandwidth", value: "Max. 80/80/60 Mbps (Incoming/Recording/Outgoing)" },
      { label: "AI by NVR", value: "Supports 4 Channel IMD" },
      { label: "AI by Camera", value: "Perimeter Protection, IMD" },
      { label: "HDD Interface", value: "1 SATA HDD up to 20TB" },
      { label: "USB Ports", value: "2 × USB" },
      { label: "Video Output", value: "1 × HDMI, 1 × VGA" },
      { label: "Network", value: "1 × RJ45" },
      { label: "Mobile App", value: "iCMOB, gCMOB" },
      { label: "CMS Software", value: "KVMS Pro Lite" }
    ],
    inBox: ["1x NVR Unit", "Power Adapter", "Mouse", "Quick Start Guide", "Warranty Card"]
  },
  {
    id: 11,
    name: "CP-UNR-4K2082-V3",
    brand: "CP Plus",
    category: "kit",
    tag: "NVR",
    tagColor: "#1565c0",
    subtitle: "8 Ch. 4K Network Video Recorder",
    image: "dvr_box.png",
    images: ["dvr_box.png", "nvr_8ch.png", "kit_8cam.png"],
    shortDesc: "8Ch 4K NVR — Industrial Processor, H.265, ONVIF, 2 SATA HDD.",
    description: "The CP-UNR-4K2082-V3 is a professional-grade 8-channel 4K NVR with an industrial-grade processor and Embedded Linux OS. Supports Instastream, H.265, Smart H.264+ compression, HDMI/VGA simultaneous output, and is compatible with multi-brand ONVIF cameras.",
    highlights: [
      "Industrial-Grade Processor",
      "Embedded Linux OS",
      "H.265 / Smart H.264+ Compression",
      "2 SATA HDDs up to 20TB",
      "HDMI + VGA Simultaneous Output",
      "ONVIF Compatible – Multi-brand Support"
    ],
    specs: [
      { label: "Model", value: "CP-UNR-4K2082-V3" },
      { label: "Type", value: "8 Ch. 4K Network Video Recorder" },
      { label: "Processor", value: "Industrial-grade Processor" },
      { label: "OS", value: "Embedded Linux" },
      { label: "Video Compression", value: "Instastream, H.265, Smart H.264+, H.264" },
      { label: "Max. Decoding", value: "6 × 1080p@30fps" },
      { label: "Bandwidth", value: "Max. 80/80/60 Mbps (Incoming/Recording/Outgoing)" },
      { label: "HDD Interface", value: "2 SATA HDDs up to 20TB each" },
      { label: "USB Ports", value: "2 × USB" },
      { label: "Video Output", value: "HDMI + VGA Simultaneous" },
      { label: "Protocol", value: "ONVIF Supported" },
      { label: "Camera Support", value: "Multi-brand Network Cameras" },
      { label: "Mobile App", value: "iCMOB, gCMOB" },
      { label: "CMS Software", value: "KVMS, KVMS Pro Lite" }
    ],
    inBox: ["1x NVR Unit", "Power Adapter", "2× SATA Cable", "Mouse", "Quick Start Guide", "Warranty Card"]
  },
  {
    id: 12,
    name: "CP-UCK-TD62N-B1",
    brand: "CP Plus",
    category: "kit",
    tag: "Complete Kit",
    tagColor: "#e53935",
    subtitle: "2.4MP 6 Bullet + 2 Dome + 8Ch DVR Kit with Accessories",
    image: "kit_8cam.png",
    images: ["kit_8cam.png", "dvr_box.png", "nvr_8ch.png"],
    shortDesc: "8 Camera Complete Kit — 6 Bullet + 2 Dome + 8Ch DVR + 90m Cable.",
    description: "The CP-UCK-TD62N-B1 is a complete 8-camera surveillance kit ideal for homes, shops and small offices. Includes six 2.4MP bullet cameras, two 2.4MP dome cameras, an 8-channel DVR, 90m coaxial cable, and all required accessories. Ready to install straight out of the box.",
    highlights: [
      "6× 2.4MP Bullet Cameras",
      "2× 2.4MP Dome Cameras",
      "8 Channel DVR (without HDD)",
      "90 Mtr. Coaxial Cable Included",
      "All Accessories Included",
      "Ready-to-Install Complete Kit"
    ],
    specs: [
      { label: "Model", value: "CP-UCK-TD62N-B1" },
      { label: "Kit Contents", value: "6× Bullet + 2× Dome + 1× 8Ch DVR + Cable" },
      { label: "Bullet Camera", value: "2.4MP IR Bullet Camera (6 Pcs)" },
      { label: "Dome Camera", value: "2.4MP IR Dome Camera (2 Pcs)" },
      { label: "DVR", value: "8 Channel DVR (without HDD)" },
      { label: "Cable", value: "90 Mtr. Coaxial Cable" },
      { label: "Camera Resolution", value: "1920 × 1080 (2.4MP)" },
      { label: "IR Range", value: "20–30 Mtrs." },
      { label: "Total Cameras", value: "8 Cameras" },
      { label: "Note", value: "HDD not included — purchase separately" }
    ],
    inBox: ["6x Bullet Cameras", "2x Dome Cameras", "1x 8Ch DVR", "90m Coaxial Cable", "Power Adapters", "Mouse", "All Mounting Hardware"]
  },
  {
    id: 13,
    name: "CP-UNC-TA21L3C-Q",
    brand: "CP Plus",
    category: "outdoor",
    tag: "IP Camera",
    tagColor: "#2e7d32",
    subtitle: "2MP Network IR Bullet Camera – 30Mtr.",
    image: "bullet_ip.png",
    images: ["bullet_ip.png", "outdoor_1.jpg", "outdoor_2.jpg"],
    shortDesc: "2MP IP Bullet — H.265, Built-in Mic, PoE, IP67, IR 30m.",
    description: "The CP-UNC-TA21L3C-Q is a 2MP Network IR Bullet Camera with 1/2.8 inch PS CMOS sensor. Features Instastream H.265 compression, built-in microphone, Triple stream support, DWDR, 3D NR, and Power over Ethernet (PoE). Ideal for IP-based surveillance systems with remote viewing.",
    highlights: [
      "2MP PS CMOS – 1920×1080@25fps",
      "Built-in Microphone",
      "PoE (Power over Ethernet)",
      "H.265 / H.264 Compression",
      "IR Night Vision 30m, IP67",
      "DWDR, 3D NR, ROI, BLC, HLC"
    ],
    specs: [
      { label: "Model", value: "CP-UNC-TA21L3C-Q" },
      { label: "Image Sensor", value: "1/2.8 inch 2MP PS CMOS (0.9071 cm)" },
      { label: "Max. Resolution", value: "1920 × 1080 @ 1–25/30fps" },
      { label: "Video Compression", value: "Instastream, H.265, H.264, H.264H, H.264B, MJPEG" },
      { label: "Stream", value: "Triple Stream Support" },
      { label: "Audio", value: "Built-in Microphone" },
      { label: "Lens", value: "3.6mm Fixed" },
      { label: "IR Range", value: "30 Mtrs." },
      { label: "Weatherproof", value: "IP67" },
      { label: "Power", value: "PoE (IEEE 802.3af)" },
      { label: "Features", value: "DWDR, Day/Night ICR, 3D NR, ROI, AWB, AGC, BLC, HLC" },
      { label: "Digital Watermarking", value: "Supported" },
      { label: "Protocol", value: "ONVIF Compatible" }
    ],
    inBox: ["1x IP Bullet Camera", "Mounting Bracket", "Screws", "User Manual", "Warranty Card"]
  },
  {
    id: 14,
    name: "CP-UNC-BE21C-VMDS-Q",
    brand: "CP Plus",
    category: "indoor",
    tag: "Box Camera",
    tagColor: "#37474f",
    subtitle: "2MP Full HD WDR Network Box Camera",
    image: "box_cam.png",
    images: ["box_cam.png", "bullet_ip.png", "outdoor_1.jpg"],
    shortDesc: "2MP WDR Box Camera — C/CS Mount, 120dB WDR, Built-in Mic, SD Card.",
    description: "The CP-UNC-BE21C-VMDS-Q is a professional 2MP Full HD WDR Network Box Camera with 1/2.9 inch PS CMOS sensor. Features 120dB WDR, Defog, EIS, Quad Stream, 2/1 alarm I/O, built-in mic, Micro SD card support, and PoE for flexible deployment in critical surveillance areas.",
    highlights: [
      "2MP Full HD – 1920×1080@25fps",
      "120dB Wide Dynamic Range (WDR)",
      "C/CS Mount Lens",
      "Built-in Mic + Micro SD Card",
      "2/1 Alarm In/Out",
      "PoE + Defog + EIS"
    ],
    specs: [
      { label: "Model", value: "CP-UNC-BE21C-VMDS-Q" },
      { label: "Image Sensor", value: "1/2.9 inch 2MP PS CMOS (0.8758 cm)" },
      { label: "Max. Resolution", value: "1920 × 1080 @ 1–25/30fps" },
      { label: "Lens Mount", value: "C/CS Mount" },
      { label: "Video Compression", value: "Instastream, H.265, H.264, H.264B, H.264H, MJPEG" },
      { label: "Stream", value: "Quad Stream Support" },
      { label: "WDR", value: "120dB" },
      { label: "Features", value: "Day/Night ICR, 3D NR, Defog, ROI, EIS, AWB, AGC, BLC, HLC" },
      { label: "Alarm I/O", value: "2/1 Alarm In/Out" },
      { label: "Audio I/O", value: "1/1 Audio In/Out" },
      { label: "Storage", value: "Micro SD Card Support" },
      { label: "Audio", value: "Built-in Mic" },
      { label: "Power", value: "PoE (IEEE 802.3af)" },
      { label: "Protocol", value: "ONVIF Compatible" }
    ],
    inBox: ["1x Box Camera", "Power Adapter", "User Manual", "Warranty Card"]
  }
];

const FEATURED_IDS = [3, 4, 7, 9];
